Squwak Assignments and little updates
VATGER-Nav/fis-package pull request #3
Opened 2024-07-11 16:52 UTC by pa-ulex

Hello,

I just loaded up the FIS Package and noticed a few things and they are or will be fixed,

- CCAMS was outdated, updated in this Pull Request
- SquwakIndicator was outdated, updated in this Pull Request and also added FSW Squwak
- FSW uses 7745 IRL looking at FlightRadar

Optional Things that can be done

- [ ] Adding IDO (IDN) and ISW (IDW) to login list

2024-07-15 07:16 UTC, hannesaltmann commented
@pa-ulex does this change to the sector naming reflect recent real-world changes? 

As far as I know the sectors are named as follows:

- ISW = Sector Hamburg Overload
- IDO = Sector München Overload

2024-07-15 11:08 UTC, pa-ulex commented
> As far as I know, the sectors are named as follows:
> 
> * ISW = Sector Hamburg Overload (former Seewelle)
> * IDO = Sector München Overload
> 
> The sector indicators are not connected to a major aerodrome in those two cases.

@hannesaltmann No, I just changed them, because for me it would only make sense to name them like that. I didn’t know that they were overload sectors, because in real life the day I looked the squwaks were used

2024-07-15 11:18 UTC, hannesaltmann commented
The Squawks in this PR seem to be correct. I just would stick to the real-world sector names.

2024-07-15 11:41 UTC, pa-ulex commented
Also with the update the ese and sct need to be updated. Tegel is still in there.

2024-07-15 20:44 UTC, hannesaltmann requested changes

2024-07-15 20:44 UTC, hannesaltmann commented on EDXX/Plugins/SquawkIndicator/squawks.json
Wrong sector names here

2024-07-16 06:19 UTC, hannesaltmann approved these changes

2024-07-16 06:19 UTC, hannesaltmann approved these changes

2024-07-21 19:33 UTC, pa-ulex commented
Is it possible if someone could review the PR and merge it into the branch or shall it be in another one for 2408?

2024-07-22 17:55 UTC, merged